services:
  web:
    build: .
    ports: ["5000:5000"]
    env_file: .env
    depends_on: [db]
    command: gunicorn --bind 0.0.0.0:5000 --timeout 120 --workers 2 --reload run:app

  db:
    image: mysql:8.0
    ports: ["3306:3306"]
    env_file: .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
